#import <XCTest/XCTest.h>
#import "OCTTokenizer.h"

// Multilingual byte-identical conformance test target. Compares
// `[OCTTokenizer encode:]` against per-kernel HuggingFace Python
// `transformers==4.57.1` references for the 83 inputs in
// `multilingual_inputs.json` across the kernels in `kernelMatrix`.
//
// Inputs are categorised and stable-keyed: a divergence message cites the
// exact axis broke (japanese-voiced-kana, emoji-keycap, thai-combining-marks,
// devanagari, …). Baselines are regenerated by `Conformance/regenerate_goldens.py`.
//
// `expectedDivergences` lets the target ship green while new bug clusters
// surfaced by the corpus get triaged. Cleanup-hint pattern: removing an
// entry that has been silently fixed is a no-op (test stays green) but a
// log line prompts removal. An unexpected divergence is a hard failure.
//
// Test target structure mirrors `MultilingualConformanceTests.swift` in
// the swift-transformers PR (#360).

#pragma mark - Resource loading

static NSDictionary *OCTLoadJSONResource(NSBundle *b, NSString *name) {
    NSURL *url = [b URLForResource:name withExtension:@"json"];
    if (!url) return nil;
    NSData *data = [NSData dataWithContentsOfURL:url];
    if (!data) return nil;
    return [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
}

static NSArray *OCTLoadJSONArrayResource(NSBundle *b, NSString *name) {
    NSURL *url = [b URLForResource:name withExtension:@"json"];
    if (!url) return nil;
    NSData *data = [NSData dataWithContentsOfURL:url];
    if (!data) return nil;
    id obj = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    return [obj isKindOfClass:[NSArray class]] ? obj : nil;
}

#pragma mark - expectedDivergences

// (modelId, inputId) pairs whose encode output is known to diverge from the
// Python reference today. Each entry carries a free-form `note` documenting
// the axis. Cleanup is mechanical: remove an entry when the underlying bug
// is fixed and verify the unexpected-match log line stops firing.
typedef struct {
    NSString *modelId;   // matches metadata.model_id in the baseline JSON
    NSString *inputId;   // stable id from multilingual_inputs.json
    NSString *note;      // what we know about the divergence
} OCTExpectedDivergence;

static NSArray *OCTExpectedDivergences(void) {
    // ObjCTokenizer claims byte-identity on the 5 original families
    // (bge_small, gpt2, llama_7b, roberta_base, t5_small) — that's the
    // contract OCTMultilingualGoldenTests.m enforces. The two new families
    // (Qwen2.5, TinyLlama) plus the expanded corpus (83 inputs vs the 83
    // we already exercise) may surface divergences not previously tested.
    //
    // This array starts empty: any divergence the test discovers is a
    // genuine new bug or a port issue we hadn't seen before, and should
    // be either fixed inline or added here with a note before merge.
    return @[];
}

static BOOL OCTDivergenceExpected(NSString *modelId,
                                  NSString *inputId,
                                  NSString **outNote) {
    for (NSValue *v in OCTExpectedDivergences()) {
        OCTExpectedDivergence d;
        [v getValue:&d];
        if ([d.modelId isEqualToString:modelId] && [d.inputId isEqualToString:inputId]) {
            if (outNote) *outNote = d.note;
            return YES;
        }
    }
    return NO;
}

#pragma mark - Failure diagnostics

// Windowed token diff around the first divergence point. Easier to triage
// than two long id arrays.
static NSString *OCTDivergenceReport(NSString *inputId,
                                     NSString *category,
                                     NSArray<NSNumber *> *expectedIds,
                                     NSArray<NSString *> *expectedTokens,
                                     NSArray<NSNumber *> *gotIds,
                                     OCTTokenizer *tok) {
    NSUInteger common = MIN(expectedIds.count, gotIds.count);
    NSUInteger divIdx = 0;
    while (divIdx < common && [expectedIds[divIdx] isEqualToNumber:gotIds[divIdx]]) divIdx++;
    NSUInteger lo = divIdx > 3 ? divIdx - 3 : 0;
    NSUInteger expHi = MIN(expectedIds.count, divIdx + 5);
    NSUInteger gotHi = MIN(gotIds.count,      divIdx + 5);

    NSMutableString *expWin = [NSMutableString string];
    for (NSUInteger i = lo; i < expHi; i++) {
        NSString *tk = i < expectedTokens.count ? expectedTokens[i] : @"?";
        [expWin appendFormat:@"[%@]%@ ", expectedIds[i], tk];
    }
    NSMutableString *gotWin = [NSMutableString string];
    for (NSUInteger i = lo; i < gotHi; i++) {
        NSString *tk = [tok tokenForId:gotIds[i].integerValue] ?: @"?";
        [gotWin appendFormat:@"[%@]%@ ", gotIds[i], tk];
    }

    return [NSString stringWithFormat:
        @"multilingual conformance divergence\n"
        @"  input id:    %@\n"
        @"  category:    %@\n"
        @"  divergence:  index %lu (expected len=%lu, got len=%lu)\n"
        @"  expected:    %@\n"
        @"  got:         %@",
        inputId, category,
        (unsigned long)divIdx,
        (unsigned long)expectedIds.count,
        (unsigned long)gotIds.count,
        [expWin stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]],
        [gotWin stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]]];
}

#pragma mark - Test case

@interface OCTMultilingualConformanceTests : XCTestCase
@end

@implementation OCTMultilingualConformanceTests

// Per-kernel descriptor. Mirrors the swift-transformers PR's BaselineKernel.
typedef struct {
    NSString *slug;             // matches `<slug>_multilingual_v2.json`
    NSString *tokenizerResource; // matches `<resource>.tokenizer.json`
    NSString *label;            // human-readable kernel name (for log/test name)
} OCTKernel;

- (NSArray<NSValue *> *)kernelMatrix {
    static OCTKernel kernels[] = {
        { @"bge_small",     @"bge-small-en-v1.5.tokenizer", @"BGE-small (WordPiece)" },
        { @"t5_small",      @"t5-small.tokenizer",          @"T5-small (Unigram)" },
        { @"gpt2",          @"gpt2.tokenizer",              @"GPT-2 (byte-level BPE)" },
        { @"roberta_base",  @"roberta-base.tokenizer",      @"RoBERTa-base (byte-level BPE + RobertaProcessing)" },
        { @"llama_7b",      @"llama-7b.tokenizer",          @"Llama-7B (BPE byte-fallback)" },
        { @"qwen2_5",       @"qwen2.5-0.5b.tokenizer",      @"Qwen2.5-0.5B (modern byte-level BPE)" },
        { @"tinyllama",     @"tinyllama-1.1b.tokenizer",    @"TinyLlama-1.1B-Chat (BPE byte-fallback)" },
        { @"gemma",         @"gemma-4-31b.tokenizer",       @"Gemma-4-31B (BPE + Replace + Metaspace, 262k vocab)" },
    };
    NSMutableArray<NSValue *> *out = [NSMutableArray array];
    for (NSUInteger i = 0; i < sizeof(kernels)/sizeof(OCTKernel); i++) {
        [out addObject:[NSValue valueWithBytes:&kernels[i] objCType:@encode(OCTKernel)]];
    }
    return out;
}

- (void)runConformanceForKernel:(OCTKernel)kernel {
    NSBundle *b = [NSBundle bundleForClass:self.class];

    // Load tokenizer.
    NSURL *tokURL = [b URLForResource:kernel.tokenizerResource withExtension:@"json"];
    if (!tokURL) {
        XCTSkip(@"%@.json not bundled — drop it into ObjCTokenizerTests/Resources/",
                kernel.tokenizerResource);
        return;
    }
    NSError *err = nil;
    OCTTokenizer *tok = [OCTTokenizer tokenizerWithJSONFileURL:tokURL error:&err];
    XCTAssertNotNil(tok, @"%@ tokenizer load failed: %@", kernel.label, err);

    // Load inputs.
    NSArray<NSDictionary *> *inputs = OCTLoadJSONArrayResource(b, @"multilingual_inputs");
    XCTAssertNotNil(inputs, @"multilingual_inputs.json missing or invalid");

    // Load baseline.
    NSString *baselineName = [NSString stringWithFormat:@"%@_multilingual_v2", kernel.slug];
    NSDictionary *baseline = OCTLoadJSONResource(b, baselineName);
    XCTAssertNotNil(baseline, @"%@.json missing or invalid", baselineName);

    NSDictionary *metadata = baseline[@"metadata"];
    NSArray<NSDictionary *> *entries = baseline[@"entries"];
    NSString *modelId = metadata[@"model_id"];
    XCTAssertNotNil(modelId, @"%@: missing metadata.model_id", baselineName);
    XCTAssertNotNil(entries, @"%@: missing entries", baselineName);

    // Index entries by id for O(1) lookup.
    NSMutableDictionary<NSString *, NSDictionary *> *entriesById = [NSMutableDictionary dictionary];
    for (NSDictionary *entry in entries) {
        entriesById[entry[@"id"]] = entry;
    }
    XCTAssertEqual(entriesById.count, entries.count,
                   @"%@: duplicate ids in baseline", baselineName);

    NSMutableArray<NSString *> *unexpectedDivergences = [NSMutableArray array];
    NSMutableArray<NSDictionary *> *unexpectedMatches  = [NSMutableArray array];

    for (NSDictionary *input in inputs) {
        NSString *inputId = input[@"id"];
        NSString *category = input[@"category"];
        NSString *text = input[@"text"];
        NSDictionary *expected = entriesById[inputId];
        if (!expected) continue;

        NSArray<NSNumber *> *expectedIds = expected[@"input_ids"];
        NSArray<NSString *> *expectedTokens = expected[@"tokens"];
        NSArray<NSNumber *> *got = [tok encode:text error:nil];

        BOOL matches = [got isEqualToArray:expectedIds];
        NSString *note = nil;
        BOOL expectedDiv = OCTDivergenceExpected(modelId, inputId, &note);

        if (matches) {
            if (expectedDiv) {
                [unexpectedMatches addObject:@{
                    @"inputId": inputId,
                    @"note":    note ?: @""
                }];
            }
        } else {
            if (expectedDiv) continue; // known-and-tracked, not a regression
            [unexpectedDivergences addObject:
                OCTDivergenceReport(inputId, category, expectedIds, expectedTokens, got, tok)];
        }
    }

    // Cleanup-hint surface — does NOT fail the test.
    for (NSDictionary *match in unexpectedMatches) {
        NSLog(@"[%@] expectedDivergences entry no longer applies:\n"
              @"  input id:  %@\n"
              @"  note:      %@\n"
              @"  hint:      remove this entry from OCTExpectedDivergences()",
              modelId, match[@"inputId"], match[@"note"]);
    }

    // Regression catch — IS a failure.
    if (unexpectedDivergences.count > 0) {
        NSMutableString *msg = [NSMutableString stringWithFormat:
            @"%@: %lu unexpected divergence(s) from HF Python reference.\n"
            @"If a divergence is being addressed, add an OCTExpectedDivergence "
            @"entry with a note. Otherwise this is a regression or a new bug.\n\n",
            modelId, (unsigned long)unexpectedDivergences.count];
        [msg appendString:[unexpectedDivergences componentsJoinedByString:@"\n\n"]];
        XCTFail(@"%@", msg);

        // Also dump to /tmp for easier triage when test output gets clipped.
        NSString *safe = [[kernel.slug stringByReplacingOccurrencesOfString:@"/" withString:@"_"]
                          stringByReplacingOccurrencesOfString:@" " withString:@"_"];
        NSString *path = [NSString stringWithFormat:@"/tmp/oct-conformance-%@.txt", safe];
        [msg writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:nil];
        NSLog(@"Full divergence report written to %@", path);
    }
}

#pragma mark - Per-kernel test methods

- (void)testBGESmallConformance      { OCTKernel k; [self.kernelMatrix[0] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testT5SmallConformance       { OCTKernel k; [self.kernelMatrix[1] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testGPT2Conformance          { OCTKernel k; [self.kernelMatrix[2] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testRobertaBaseConformance   { OCTKernel k; [self.kernelMatrix[3] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testLlama7bConformance       { OCTKernel k; [self.kernelMatrix[4] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testQwen2_5Conformance       { OCTKernel k; [self.kernelMatrix[5] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testTinyLlamaConformance     { OCTKernel k; [self.kernelMatrix[6] getValue:&k]; [self runConformanceForKernel:k]; }
- (void)testGemma4Conformance        { OCTKernel k; [self.kernelMatrix[7] getValue:&k]; [self runConformanceForKernel:k]; }

@end
